services:

    # Entry points: actions
    Av\Action\:
        resource: '../src/Action'
        tags: ['controller.service_arguments']
        autowire: true

    # Doctrine support for PostgreSQL 12
    Av\Common\Doctrine\PostgreSQL120Platform:
        public: true